### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by buguen** [osv-team/osvcad#4]
Dear Guillaume, 

I have modifed the setup.py in order the ccad/ui modul to be installed. 
I have now the following error message probably because my conda setup is wrong.
in running basic_assembly_two_cubes.py, I got the following trace

No PyQt4 backend 
2017-12-23 10:59:26,283 ::  DEBUG ::                nodes :: 274 :: GeometryNode.Place() GeometryNode : 139974255880784/only_anchor on GeometryNode : 139974255880656/only_anchor with angle:0.000000 distance0.000000 inplace:False
2017-12-23 10:59:26,283 ::  DEBUG ::             geometry ::  54 :: Computing transformation from 2 anchors
2017-12-23 10:59:26,283 ::  DEBUG ::             geometry ::  56 :: Master | pos : (5, 5, 10) | dir : (0, 0, 20)
2017-12-23 10:59:26,283 ::  DEBUG ::             geometry ::  58 :: Slave  | pos : (110, 10, 20) | dir : (0, 0, 20)
2017-12-23 10:59:26,283 ::  DEBUG ::             geometry ::  59 :: Distance : 0.000000
2017-12-23 10:59:26,283 ::  DEBUG ::             geometry ::  60 :: Angle : 0.000000
2017-12-23 10:59:26,288 ::  DEBUG ::             geometry ::  71 :: Angle between anchors : 0.000000 deg
2017-12-23 10:59:26,290 ::  DEBUG ::             geometry :: 136 :: ... Done computing transformation from 2 anchors

(basic_assembly_two_cubes.py:9442): Gdk-WARNING **: /build/gtk+2.0-jJZIsQ/gtk+2.0-2.24.30/gdk/x11/gdkdrawable-x11.c:952 drawable is not a pixmap or window
 ###### 3D rendering pipe initialisation #####
Display3d class initialization starting ...
Aspect_DisplayConnection created.
Graphic_Driver created.
V3d_Viewer created.
AIS_InteractiveContext created.
V3d_View created
Traceback (most recent call last):
  File "basic_assembly_two_cubes.py", line 82, in <module>
    main()
  File "basic_assembly_two_cubes.py", line 55, in main
    frame = MyFrame()
  File "basic_assembly_two_cubes.py", line 51, in __init__
    self.p = Wx3dViewer(self)
  File "/home/uguen/anaconda2/envs/ccad/lib/python2.7/site-packages/aocutils-0.4.2-py2.7.egg/aocutils/display/wx_viewer.py", line 26, in __init__
    self.viewer.InitDriver()
  File "/home/uguen/anaconda2/envs/ccad/lib/python2.7/site-packages/OCC/Display/wxDisplay.py", line 113, in InitDriver
    self._display.Create()
  File "/home/uguen/anaconda2/envs/ccad/lib/python2.7/site-packages/OCC/Display/OCCViewer.py", line 155, in Create
    self.Init(int(self._window_handle))
RuntimeError: Aspect_WindowDefinitionError
Xw_Window, given invalid X window

**Comment by buguen** [comment]
The installation of the last version of pythonOCC with 

conda install -c conda-forge -c dlr-sc -c pythonocc -c oce pythonocc-core==0.18.1

do not fix the problem, nevertheless the error message is modified 

   raise AssertionError("Can't get win Id")
AssertionError: Can't get win Id

This is my conda list of package 

es in environment at /home/uguen/anaconda2/envs/ccad:
#
alabaster                 0.7.10                   py27_0  
aocutils                  0.4.2                     <pip>
astroid                   1.4.9                    py27_0  
babel                     2.4.0                    py27_0  
backports                 1.0                      py27_0  
backports_abc             0.5                      py27_0  
bleach                    1.5.0                    py27_0  
cairo                     1.14.6                        4    conda-forge
ccad                      0.13                      <pip>
chardet                   3.0.3                    py27_0  
chrpath                   0.16                          0    conda-forge
configparser              3.5.0                    py27_0  
cycler                    0.10.0                   py27_0  
dbus                      1.10.10                       0  
decorator                 4.0.11                   py27_0  
docutils                  0.13.1                   py27_0  
entrypoints               0.2.2                    py27_1  
enum34                    1.1.6                    py27_0  
expat                     2.1.0                         0  
fontconfig                2.12.1                        4    conda-forge
freeimage                 3.17.0                        1  
freeimageplus             3.17.0                        0    dlr-sc
freetype                  2.7                           1    conda-forge
functools32               3.2.3.2                  py27_0  
get_terminal_size         1.0.0                    py27_0  
gettext                   0.19.7                        1    conda-forge
gl2ps                     1.3.8                         1    dlr-sc
glib                      2.51.4                        0    conda-forge
gmp                       6.1.2                         0    conda-forge
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
html5lib                  0.999                    py27_0  
icu                       58.1                          1    conda-forge
imagesize                 0.7.1                    py27_0  
ipykernel                 4.6.1                    py27_0  
ipython                   5.3.0                    py27_0  
ipython_genutils          0.2.0                    py27_0  
isort                     4.2.14                   py27_0  
jedi                      0.10.2                   py27_2  
jinja2                    2.9.6                    py27_0  
jpeg                      9b                            0  
jsonpickle                0.9.4                     <pip>
jsonschema                2.6.0                    py27_0  
jupyter_client            5.0.1                    py27_0  
jupyter_core              4.3.0                    py27_0  
lazy-object-proxy         1.2.2                    py27_0  
libffi                    3.2.1                         1  
libgcc                    5.2.0                         0  
libgfortran               3.0.0                         1  
libiconv                  1.14                          0  
libpng                    1.6.28                        1    conda-forge
libsodium                 1.0.10                        0  
libuuid                   1.0.3                         1    conda-forge
libxcb                    1.12                          1  
libxml2                   2.9.3                         1    dlr-sc
markupsafe                0.23                     py27_2  
matplotlib                2.0.2                    py27_2    conda-forge
mistune                   0.7.4                    py27_0  
mkl                       2017.0.1                      0  
nbconvert                 5.2.1                    py27_0  
nbformat                  4.3.0                    py27_0  
ncurses                   5.9                          10    conda-forge
networkx                  1.11                     py27_0  
numpy                     1.13.0                   py27_0  
numpydoc                  0.6.0                    py27_0  
oce                       0.18.2               h49dc8cd_2    oce
openssl                   1.0.2l                        0  
osvcad                    0.2.0                     <pip>
pandocfilters             1.4.1                    py27_0  
path.py                   10.3.1                   py27_0  
pathlib2                  2.2.1                    py27_0  
pcre                      8.39                          1  
pep8                      1.7.0                    py27_0  
pexpect                   4.2.1                    py27_0  
pickleshare               0.7.4                    py27_0  
pip                       9.0.1                    py27_1  
pixman                    0.34.0                        0  
prompt_toolkit            1.0.14                   py27_0  
psutil                    5.2.2                    py27_0  
ptyprocess                0.5.1                    py27_0  
pycairo                   1.10.0                   py27_0  
pyflakes                  1.5.0                    py27_0  
pygments                  2.2.0                    py27_0  
pylint                    1.6.4                    py27_1  
pyparsing                 2.1.4                    py27_0  
pyqt                      5.6.0                    py27_2  
pyside                    1.2.0                    py27_0  
python                    2.7.13                        1    conda-forge
python-dateutil           2.6.0                    py27_0  
pythonocc-core            0.18.1          py27h0e62f72_110    pythonocc
pytz                      2017.2                   py27_0  
pyzmq                     16.0.2                   py27_0  
qt                        5.6.2                         5    conda-forge
qtawesome                 0.4.4                    py27_0  
qtconsole                 4.3.0                    py27_0  
qtpy                      1.2.1                    py27_0  
readline                  6.2                           2  
requests                  2.14.2                   py27_0  
rope                      0.9.4                    py27_1  
ruby                      2.4.1                         0    conda-forge
scandir                   1.5                      py27_0  
scipy                     0.19.0              np113py27_0  
setuptools                27.2.0                   py27_0  
shiboken                  1.2.1                    py27_0  
simplegeneric             0.8.1                    py27_1  
singledispatch            3.4.0.3                  py27_0  
sip                       4.18                     py27_0  
six                       1.10.0                   py27_0  
smesh                     6.7.5                         0    pythonocc
snowballstemmer           1.2.1                    py27_0  
sphinx                    1.6.2                    py27_0  
sphinxcontrib             1.0                      py27_0  
sphinxcontrib-websupport  1.0.1                    py27_0  
sqlite                    3.13.0                        0  
ssl_match_hostname        3.4.0.2                  py27_1  
subprocess32              3.2.7                    py27_0  
tbb                       2017_20170226                 0    conda-forge
tblib                     1.3.2                    py27_0  
testpath                  0.3.1                    py27_0  
tk                        8.5.18                        0  
tornado                   4.5.1                    py27_0  
traitlets                 4.3.2                    py27_0  
typing                    3.6.1                    py27_0  
wcwidth                   0.1.7                    py27_0  
wheel                     0.29.0                   py27_0  
wrapt                     1.10.10                  py27_0  
wxpython                  3.0.0.0                  py27_2  
xorg-kbproto              1.0.7                         1    conda-forge
xorg-libice               1.0.9                         2    conda-forge
xorg-libsm                1.2.2                         2    conda-forge
xorg-libx11               1.6.4                         6    conda-forge
xorg-libxext              1.3.3                         2    conda-forge
xorg-libxrender           0.9.10                        0    conda-forge
xorg-libxt                1.1.5                         0    conda-forge
xorg-renderproto          0.11.1                        1    conda-forge
xorg-xextproto            7.3.0                         1    conda-forge
xorg-xproto               7.0.31                        6    conda-forge
yaml                      0.1.6                         0    conda-forge
zeromq                    4.1.5                         0  
zlib                      1.2.8                         3

**Comment by buguen** [comment]
May by due to pyqt5

**Comment by buguen** [comment]
pythonOcc requires pyqt>5

pythonocc-core -> pyqt >=5

**Comment by guillaume-florent** [comment]
"Can't get win Id" is a wxpython bug on Linux platforms. Regarding PyQt, all pyosv projects are now targeting v5 when they use PyQt. I will close this issue and open another regarding wx's "Can't get win Id"
